apiVersion: v1
kind: Pod
metadata:
  name: mypod-secret
spec:
  containers:
  - name: mypod
    image: redis
    volumeMounts:
    - name: secret-vol
      mountPath: /etc/foo
      readOnly: true
  volumes:
  - name: secret-vol
    secret:
      secretName: app-secret

